Exam2/Controllers/ActivityController.cs
using Exam2.Models.Interfaces;
using Exam2.Models.Services;
using Exam2.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Exam2.Controllers;

public class ActivityController : Controller
{
    private readonly IActivityService _activityService;
    private readonly IMemberService _memberService;

    public ActivityController(IActivityService activityService, IMemberService memberService)
    {
        _activityService = activityService;
        _memberService = memberService;
    }

    public async Task<IActionResult> Index([FromQuery]string activityName, [FromQuery]string startDate, [FromQuery]string endDate)
    {
        var activitySearchViewModel = new ActivitySearchViewModel
        {
            ActivityNameCondition = activityName,
            StartDateCondition = startDate,
            EndDateCondition = endDate,
        };

        var activityListQuery = await _activityService.ActivityListQueryAsync(activitySearchViewModel);

        return View(activityListQuery);
    }

    public async Task<IActionResult> Detail(string id, string actionType)
    {
        ViewData["actionType"] = actionType;
        if (actionType == "Add")
            return View(new ActivityDetailViewModel{UnSelectCheckBoxes = await _memberService.GetAllMemberList()});
        var activity = await _activityService.ActivityListQueryByIdAsync(id);

        return View(activity);
    }

    [HttpPost]
    public async Task<IActionResult> ActivityAdd([FromBody]ActivityDetailViewModel activityDetailViewModel)
    {
        if (!ModelState.IsValid && ModelStateInValid(activityDetailViewModel, ModelState))
            return BadRequest(ModelState);
        var result = await _activityService.ActivityAddAsync(activityDetailViewModel);
        return Json(result);
    }

    [HttpPost]
    public async Task<IActionResult> ActivityEdit([FromBody]ActivityDetailViewModel activityDetailViewModel)
    {
        if (!ModelState.IsValid && ModelStateInValid(activityDetailViewModel, ModelState))
            return BadRequest(ModelState);
        var result = await _activityService.ActivityEditAsync(activityDetailViewModel);
        return Json(result);
    }

    private static bool ModelStateInValid(ActivityDetailViewModel activityDetailViewModel, ModelStateDictionary modelStateDictionary)
    {
        var modelStateKeys = new List<string>();
        foreach (var propertyInfo in activityDetailViewModel.GetType().GetProperties())
        {
            if ((propertyInfo.PropertyType == typeof(int) || propertyInfo.PropertyType == typeof(string)) && modelStateDictionary.ContainsKey(propertyInfo.Name))
            {
                return true;
            }
        }

        return false;
    }
}

Exam2/Controllers/MemberController.cs
using AutoMapper.Execution;
using Exam2.Models.Interfaces;
using Exam2.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Exam2.Controllers;

public class MemberController : Controller
{
    private readonly IMemberService _memberService;

    public MemberController(IMemberService memberService)
    {
        _memberService = memberService;
    }

    public async Task<IActionResult> Index([FromQuery]string nameCondition, [FromQuery]string birthdayYearCondition)
    {
        var memberSearchViewModel = new MemberSearchViewModel
        {
            NameCondition = nameCondition,
            BirthdayYearCondition = birthdayYearCondition
        };
        var memberListQuery = await _memberService.MemberListQuery(memberSearchViewModel);
        
        return View(memberListQuery);
    }

    public async Task<IActionResult> Detail(string id, string actionType)
    {
        var memberQueryById = await _memberService.MemberQueryById(id);
        ViewData["actionType"] = actionType;
        ViewBag.sexList = SexListSetting(memberQueryById.Sex);

        return View(memberQueryById);
    }
    
    private static List<SelectListItem> SexListSetting(string sex)
    {
        return new List<SelectListItem>
        {
            new SelectListItem
            {
                Text = "男",
                Value = "M",
                Selected = sex == "M" || string.IsNullOrWhiteSpace(sex),
            },
            new SelectListItem
            {
                Text = "女",
                Value = "F",
                Selected = sex == "F",
            },
        };
    }

    [HttpPost]
    public async Task<IActionResult> MemberAdd([FromBody]MemberDetailViewModel memberDetailViewModel)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);
        var result = await _memberService.MemberAddAsync(memberDetailViewModel);
        if (!result.Item1)
        {
            ModelState.AddModelError(nameof(memberDetailViewModel.IdentityNumber), result.Item2);
            return BadRequest(ModelState);
        }
            
        return Json(true);
    }

    [HttpPost]
    public async Task<IActionResult> MemberEdit([FromBody]MemberDetailViewModel memberDetailViewModel)
    {
        if (!ModelState.IsValid) return BadRequest(ModelState);
        var result = await _memberService.MemberEditAsync(memberDetailViewModel);
        if (!result.Item1)
        {
            ModelState.AddModelError(nameof(memberDetailViewModel.IdentityNumber), result.Item2);
            return BadRequest(ModelState);
        }
            
        return Json(true);
    }
}

Exam2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exam1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Exam1.styles.css" asp-append-version="true" />
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Majestic Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/vendors/base/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/favicon.png" />
    <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
  <div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="navbar-brand-wrapper d-flex justify-content-center">
        <div class="navbar-brand-inner-wrapper d-flex justify-content-between align-items-center w-100">  
          <a class="navbar-brand brand-logo" href="index.html"><img src="images/logo.svg" alt="logo"/></a>
          <a class="navbar-brand brand-logo-mini" href="index.html"><img src="images/logo-mini.svg" alt="logo"/></a>
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-sort-variant"></span>
          </button>
        </div>  
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <ul class="navbar-nav mr-lg-4 w-100">
          <li class="nav-item nav-search d-none d-lg-block w-100">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
              </div>
              <input type="text" class="form-control" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown mr-1">
            <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-message-text mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="images/faces/face4.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">David Grey
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    The meeting is cancelled
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="images/faces/face2.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal">Tim Cook
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    New product launch
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                    <img src="images/faces/face3.jpg" alt="image" class="profile-pic">
                </div>
                <div class="item-content flex-grow">
                  <h6 class="ellipsis font-weight-normal"> Johnson
                  </h6>
                  <p class="font-weight-light small-text text-muted mb-0">
                    Upcoming board meeting
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item dropdown mr-4">
            <a class="nav-link count-indicator dropdown-toggle d-flex align-items-center justify-content-center notification-dropdown" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="mdi mdi-bell mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-success">
                    <i class="mdi mdi-information mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-warning">
                    <i class="mdi mdi-settings mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item">
                <div class="item-thumbnail">
                  <div class="item-icon bg-info">
                    <i class="mdi mdi-account-box mx-0"></i>
                  </div>
                </div>
                <div class="item-content">
                  <h6 class="font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="images/faces/face5.jpg" alt="profile"/>
              <span class="nav-profile-name">@User.Identity?.Name</span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item">
                <i class="mdi mdi-settings text-primary"></i>
                Settings
              </a>
              <a class="dropdown-item" href="/">
                <i class="mdi mdi-logout text-primary"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item">
            <a class="nav-link" href="/">
              <i class="mdi mdi-home menu-icon"></i>
              <span class="menu-title">Home</span>
            </a>
          </li>
          @* <li class="nav-item"> *@
          @*   <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic"> *@
          @*     <i class="mdi mdi-circle-outline menu-icon"></i> *@
          @*     <span class="menu-title">UI Elements</span> *@
          @*     <i class="menu-arrow"></i> *@
          @*   </a> *@
          @*   <div class="collapse" id="ui-basic"> *@
          @*     <ul class="nav flex-column sub-menu"> *@
          @*       <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li> *@
          @*       <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li> *@
          @*     </ul> *@
          @*   </div> *@
          @* </li> *@
          <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Member")">
              <i class="mdi mdi-view-headline menu-icon"></i>
              <span class="menu-title">會員資料</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="@Url.Action("Index", "Activity")">
              <i class="mdi mdi-view-headline menu-icon"></i>
              <span class="menu-title">活動資料</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/charts/chartjs.html">
              <i class="mdi mdi-chart-pie menu-icon"></i>
              <span class="menu-title">Charts</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/tables/basic-table.html">
              <i class="mdi mdi-grid-large menu-icon"></i>
              <span class="menu-title">Tables</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="pages/icons/mdi.html">
              <i class="mdi mdi-emoticon menu-icon"></i>
              <span class="menu-title">Icons</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
              <i class="mdi mdi-account menu-icon"></i>
              <span class="menu-title">User Pages</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="auth">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="pages/samples/login.html"> Login </a></li>
                <li class="nav-item"> <a class="nav-link" href="pages/samples/login-2.html"> Login 2 </a></li>
                <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
                <li class="nav-item"> <a class="nav-link" href="pages/samples/register-2.html"> Register 2 </a></li>
                <li class="nav-item"> <a class="nav-link" href="pages/samples/lock-screen.html"> Lockscreen </a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="documentation/documentation.html">
              <i class="mdi mdi-file-document-box-outline menu-icon"></i>
              <span class="menu-title">Documentation</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="main-panel">
        <div class="content-wrapper">
          @RenderBody()
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:partials/_footer.html -->
        <footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2018 <a href="https://www.urbanui.com/" target="_blank">Urbanui</a>. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="mdi mdi-heart text-danger"></i></span>
          </div>
        </footer>
        <!-- partial -->
      </div>
      <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
  </div>
  <!-- container-scroller -->

  <!-- plugins:js -->
  <script src="vendors/base/vendor.bundle.base.js"></script>
  <!-- endinject -->
  <!-- Plugin js for this page-->
  <script src="vendors/chart.js/Chart.min.js"></script>
  <script src="vendors/datatables.net/jquery.dataTables.js"></script>
  <script src="vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
  <!-- End plugin js for this page-->
  <!-- inject:js -->
  <script src="js/off-canvas.js"></script>
  <script src="js/hoverable-collapse.js"></script>
  <script src="js/template.js"></script>
  <!-- endinject -->
  <!-- Custom js for this page-->
  <script src="js/dashboard.js"></script>
  <script src="js/data-table.js"></script>
  <script src="js/jquery.dataTables.js"></script>
  <script src="js/dataTables.bootstrap4.js"></script>
@await RenderSectionAsync("Scripts", required: false)
  <!-- End custom js for this page-->
</body>
</html>